language: c
sudo: required
env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.6
os:
  - linux
  - osx
osx_image: xcode9.1
install: 
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        MINICONDA_VERSION=2 ;
    else
        MINICONDA_VERSION=3 ;
    fi ;

    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINICONDA_OS=Linux ;
    else
        MINICONDA_OS=MacOSX ;
    fi ;
    wget https://repo.continuum.io/miniconda/Miniconda$MINICONDA_VERSION-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
branches:
    only: pyjnius
script:
  - ./travis.sh

