# You can use this environment to run the tests, when PyImageJ will be
# installed from source
name: imagej
channels:
  - conda-forge
  - defaults
dependencies:
  - imglyb
  - ipywidgets
  - jpype1
  - jupyter_contrib_nbextensions
  - matplotlib-base
  - notebook
  - numpy
  - openjdk=8
  - scikit-image
  - scyjava
  - xarray

  - pytest
  - pytest-cov
